### ISSUE TITLE
Add ISO15765 support

### ISSUE THREAD

**Issue by ieffuie4** [fenugrec/freediag#101]
I have already find out, that this is planned, but there was no 'classic' issue report for this that is often used for discussion. So i make it here.

**Comment by fenugrec** [comment]
I suppose I should update the docs to state that 15765 is, in fact, not planned. Where did you find this mentioned ?
Someone else would have to volunteer to implement it and that is not a small task.

**Comment by ieffuie4** [comment]
On the website of the project that is linked in [README.md](https://github.com/fenugrec/freediag/blob/master/README.md)
https://freediag.sourceforge.io/
Its there in the Roadmap of the project.

**Comment by fenugrec** [comment]
will update the website "later"
