### ISSUE TITLE
scantool: Truncated formatted print

### ISSUE THREAD

**Issue by nsajko** [fenugrec/freediag#30]
It seems that this buffer is too small, the snprintf calls truncate their output:
https://github.com/fenugrec/freediag/blob/0759f5fa300e3416a094e04e6668674522eda05a/scantool/diag_l3_saej1979.c#L548

See here:
https://drive.google.com/file/d/0B63rdrZtwIE9Vkdta1h6T1BvN1E/view?usp=sharing

**Comment by fenugrec** [comment]
indeed ! good catch, that would be a good test to add to the test suite.

**Comment by fenugrec** [comment]
What is generating those warnings ?
