### ISSUE TITLE
scantool_850.c formatted print errors

### ISSUE THREAD

**Issue by nsajko** [fenugrec/freediag#33]
GCC gives more warnings:

https://gist.github.com/nsajko/eecf8e074e9b918f491a63bee9f17a7a

**Comment by fenugrec** [comment]
Partial fix in 9c32372c9f8b598f1e6c92ff90c80d697bb0094f

**Comment by fenugrec** [comment]
I think this is fixed ? I added -Wformat-overflow and not getting any warnings with gcc 10.2
