### ISSUE TITLE
Software asked to report this..

### ISSUE THREAD

**Issue by PrzemoF** [fenugrec/freediag#4]
I use ELM327 over usb on /dev/ttyUSB0

$ sudo ./scantool 
scantool: Interface set to default: CARSIM on /dev/null
scantool: freediag version 1.07
scantool: Type HELP for a list of commands
scantool: Type SCAN to start ODBII Scan
scantool: Then use MONITOR to monitor real-time data
scantool: **** IMPORTANT : this is beta software ! Use at your own risk.
scantool: **** Remember, "debug all -1" displays all debugging info.
interface is now ELM on /dev/ttyUSB0
hardware interface: use "set interface NAME [dev]" .
NAME is the interface type and [dev] is
a complete device path such as "/dev/ttyS0" or "\\.\COM11"
Valid NAMEs are: 
MET16 BR1 ELM CARSIM DUMB DUMBT 
Valid ports:
	 0 : /dev/ttyUSB0
scantool: Settings loaded from scantool.ini

scantool> scan

Trying SAEJ1850-VPW:
clock_gettime(): using CLOCK_MONOTONIC_RAW
clock_nanosleep(): using CLOCK_MONOTONIC
diag_os_gethrt() resolution <= 0us, avg ~0us
diag_os_getms() resolution <= ~1ms, avg ~1ms
testing diag_os_millisleep(), this will take a moment...
diag_os_chronoms() : initial time 1459089321879ms; resolution: ~1ms
>LM327 v1.4 not recognized! Please report this ! Resp=
L2 connection OK; tring to add SAE J1979 layer...
diag_l2.c:588: Illegal error code: 0x00
.
diag_l3.c:333: Illegal error code: 0x00
.
diag_l3.c:238: Illegal error code: 0x00
.
diag_l3_saej1979.c:716: Read/Write timeout.
diag_l3_saej1979.c:745:  J1979 Keepalive failed ! Try to disconnect and reconnect.
diag_l3_saej1979.c:748: Read/Write timeout.
diag_l3.c:110: Read/Write timeout.
Failed to enable SAEJ1979 mode

Trying SAEJ1850-PWM:
>LM327 v1.4 not recognized! Please report this ! Resp=
L2 connection OK; tring to add SAE J1979 layer...
diag_l2.c:588: Illegal error code: 0x00
.
diag_l3.c:333: Illegal error code: 0x00
.
diag_l3.c:238: Illegal error code: 0x00
.
diag_l3_saej1979.c:716: Read/Write timeout.
diag_l3_saej1979.c:745:  J1979 Keepalive failed ! Try to disconnect and reconnect.
diag_l3_saej1979.c:748: Read/Write timeout.
diag_l3.c:110: Read/Write timeout.
Failed to enable SAEJ1979 mode

Trying ISO14230_FAST:
>LM327 v1.4 not recognized! Please report this ! Resp=
Note : explicit bus init not available on clones. Errors here are ignored.
L2 connection OK; tring to add SAE J1979 layer...
ISO14230_FAST Connected.
Connection to ECU established
Exploring Mode 0x01 supported PIDs (block 0x00)...
Exploring Mode 0x01 supported PIDs (block 0x20)...
Exploring Mode 0x02 supported PIDs (block 0x00)...
Exploring Mode 0x05 supported PIDs (block 0x00)...
Exploring Mode 0x06 supported PIDs (block 0x00)...
Exploring Mode 0x08 supported PIDs (block 0x00)...
Exploring Mode 0x09 supported PIDs (block 0x00)...
Requesting Mode 0x01 PID 0x01 (Current DTCs)...
MIL light OFF, 0 stored DTCs
Requesting Mode 1 Pid 0x03...
Requesting Mode 1 Pid 0x04...
Requesting Mode 1 Pid 0x05...
Requesting Mode 1 Pid 0x06...
Requesting Mode 1 Pid 0x07...
Requesting Mode 1 Pid 0x0B...
Requesting Mode 1 Pid 0x0C...
Requesting Mode 1 Pid 0x0D...
Requesting Mode 1 Pid 0x0E...
Requesting Mode 1 Pid 0x0F...
Requesting Mode 1 Pid 0x10...
Requesting Mode 1 Pid 0x11...
Requesting Mode 1 Pid 0x12...
Requesting Mode 1 Pid 0x13...
Requesting Mode 1 Pid 0x15...
Requesting Mode 1 Pid 0x1C...
Requesting Mode 1 Pid 0x20...
Requesting Mode 1 Pid 0x21...
Requesting Mode 1 Pid 0x24...
Requesting Mode 0x02 Pid 0x02 (Freeze frame DTCs)...
ECU 0 is EOBD (Europe) compliant
Requesting Mode 0x01 PID 0x13 (O2 sensors location)...
2 Oxygen (O2) sensors in vehicle
Oxygen (O2) sensor tests not supported
Requesting Mode 7 (Current cycle emission DTCs)...
Currently monitored DTCs: 
Non-continuously monitored system tests (failures only): -
Requesting Mode 6 TestID 0x01...
Requesting Mode 6 TestID 0x02...
Requesting Mode 6 TestID 0x03...
Requesting Mode 6 TestID 0x06...
Requesting Mode 6 TestID 0x07...
Requesting Mode 6 TestID 0x08...
Requesting Mode 6 TestID 0x09...
scantool> exit

**Comment by fenugrec** [comment]
Thanks for the report. Note that your ELM cable uses a clone IC; I do not recommend those. But yes, they usually work, as the rest of your log shows.
In any case, I just committed
- 3185846f29c419c2178e15715f9a573727b20fcf fix the "Version not recognized" message;
- 2d818833ded78b9f6cd020c9842b001d97e22efe fix the "Illegal error code : 0x00" .
They are minor fixes which shouldn't prevent you from using freediag; they will be included in the next release.
Thanks!
