### ISSUE TITLE
Freediags Linux binary shouldn't be called scantool

### ISSUE THREAD

**Issue by plater** [fenugrec/freediag#53]
I'm busy packaging freediag for openSUSE (and myself) and I've patched the build to produce /usr/bin/freediag instead of scantool due to the fact that scantool already exists and is available in Ubuntu and debian.
[freediag-rename-scantool.patch.txt](https://github.com/fenugrec/freediag/files/3077422/freediag-rename-scantool.patch.txt)
Besides Linux users are used to names unrelated to functions.
https://build.opensuse.org/package/show/home:plater/scantool

**Comment by fenugrec** [comment]
Thanks, I will look at this. It's not the first time packagers have name collisions wiht scantool.net VS freediag.
To be complete however the docs should be patched too, at least the direct references to the CLI binary.

**Comment by plater** [comment]
> Thanks, I will look at this. It's not the first time packagers have name collisions wiht scantool.net VS freediag.
> To be complete however the docs should be patched too, at least the direct references to the CLI binary.

I realize that the patch is "WIP", I also plan on working on the can implementation.

**Comment by fenugrec** [comment]
I tried applying your patch against c33eab1 :
```
$ git apply freediag-rename-scantool.patch.txt
error: patch failed: CMakeLists.txt:106
error: CMakeLists.txt: patch does not apply
```
what's your patch command to make this work ?

**Comment by plater** [comment]
Sorry, it was made with -p0, this one should work after renaming. -p0 is a bad habit I have, git uses -p1
[freediag-rename-scantool.patch.txt](https://github.com/fenugrec/freediag/files/3201381/freediag-rename-scantool.patch.txt)

**Comment by fenugrec** [comment]
Thanks, that worked. Applied in 896e75b with doc fixups.
