### ISSUE TITLE
OBD 2 bluetooth interface support

### ISSUE THREAD

**Issue by erotavlas85** [fenugrec/freediag#7]
Hi,
I'm looking for a obd 2 bluetooth interface that is compatible with protocol ELM 327. I can find very cheap (less than 10 €) model on ebay http://www.ebay.it/sch/i.html?_odkw=obd2+bluetooth+4&_osacat=0&_from=R40&_trksid=p2045573.m570.l1313.TR0.TRC0.H0.Xobd2+bluetooth.TRS0&_nkw=obd2+bluetooth&_sacat=0 up to quite expensive (about 70 €) model here https://www.scantool.net/scan-tools/pc-based/obdlink-mxbt/.
What are the main differences? I know that expensive model allows to manage also error codes.
What do you recommend? Something compatible with GNU/linux?
Thank you

**Comment by fenugrec** [comment]
I have no experience with bluetooth devices, but I can assure you the cheapest units you find are guaranteed to contain an inferior, cloned ELM327 IC that doesn't support all the commands that a genuine 327 would. There probably are existing products halfway between the two you linked, that have a real ELM327. I don't have any recommendations at this time, sorry.
As for compatibility, any device that responds to elm327 commands over a serial port (real, USB-serial, or bluetooth-serial), should work with freediag.
