### ISSUE TITLE
cannot connect to Chrysler Voyager

### ISSUE THREAD

**Issue by DavidCprog** [fenugrec/freediag#78]
fails at scantool_diag.c Line 365 which leads to iInitbus type not supported by HW.
Presently looking at C code to see for myself. 
There's a good possibility it has nothing to do with the program.
My 2000 Chrysler Voyager passed the inspection scan but failed autoparts scanner, my sears scanner, the ELM327 with an iPhone and freediag run from Laptop.  Chrysler Voyager has OBDII but there's an excellent possibility it has it's own protocol.     
I'm lightly familiar with the SCI & CCD data lines.
Thanks ahead for your time   Dave

**Comment by aaeegg** [comment]
@DavidCprog what country was this van sold in?
