### ISSUE TITLE
compile error on Mac OSX

### ISSUE THREAD

**Issue by alan707** [fenugrec/freediag#8]
when compiling with make on Mac OSX El Capitan 10.11.5 (15F34), I get the following error:
`$home/.../freediag/scantool/diag.h:34:10: fatal error: 'cconf.h' file not found
#include "cconf.h"
`
There is a file called `freediag/cconf.h.in`.  How do you go from `cconf.h.in` to `cconf.h`so that the make compiler can read it?

**Comment by alan707** [comment]
I used cmake version 3.2.1 installed using command:
`brew install cmake`

**Comment by fenugrec** [comment]
Please read doc/build_system.txt , "instructions for cmake"

**Comment by fenugrec** [comment]
@alan707 what is the status on this, can the issue be closed ?

**Comment by fenugrec** [comment]
Please re-open if you have details to add. Thanks !
